version: "3.9"
services:
# PostgreSQL
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgresuser"
      POSTGRES_PASSWORD: "postgres-pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresuser -d postgres"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

volumes:
  pg-data:

#Docker Networks
networks:
  pg-network:
    driver: bridge